### ISSUE TITLE
impossible to import the bip_utils module

### ISSUE THREAD

**Issue by Lavatoto** [yaron4u/EnigmaCracker#3]
PS C:\Users\conta\Desktop\EnigmaCracker-main\EnigmaCracker> pip install bip_utils 
Collecting bip_utils
  Using cached bip_utils-2.8.0-py3-none-any.whl.metadata (12 kB)
Collecting cbor2~=5.1 (from bip_utils)
  Using cached cbor2-5.5.1-cp312-cp312-win_amd64.whl.metadata (6.1 kB)
Requirement already satisfied: coincurve<19.0.0,>=15.0.1 in c:\users\conta\appdata\local\programs\python\python312\lib\site-packages (from bip_utils) (17.0.0)
Collecting crcmod~=1.7 (from bip_utils)
  Using cached crcmod-1.7.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ecdsa~=0.15 in c:\users\conta\appdata\local\programs\python\python312\lib\site-packages (from bip_utils) (0.18.0)
Collecting ed25519-blake2b~=1.4 (from bip_utils)
  Using cached ed25519-blake2b-1.4.tar.gz (871 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\conta\AppData\Local\Temp\pip-install-5bu4yadr\ed25519-blake2b_08a32b6ab55a444c856e049c4acc888f\versioneer.py:467: SyntaxWarning: invalid escape sequence 
'\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\Users\conta\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>   
          main()
        File "C:\Users\conta\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main       
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\conta\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\conta\AppData\Local\Temp\pip-build-env-0uw0_ee6\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel   
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\conta\AppData\Local\Temp\pip-build-env-0uw0_ee6\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\conta\AppData\Local\Temp\pip-build-env-0uw0_ee6\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\conta\AppData\Local\Temp\pip-build-env-0uw0_ee6\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 109, in <module>
        File "C:\Users\conta\AppData\Local\Temp\pip-install-5bu4yadr\ed25519-blake2b_08a32b6ab55a444c856e049c4acc888f\versioneer.py", line 1405, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\conta\AppData\Local\Temp\pip-install-5bu4yadr\ed25519-blake2b_08a32b6ab55a444c856e049c4acc888f\versioneer.py", line 1339, in get_versions        
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\conta\AppData\Local\Temp\pip-install-5bu4yadr\ed25519-blake2b_08a32b6ab55a444c856e049c4acc888f\versioneer.py", line 399, in get_config_from_root 
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by yaron4u** [comment]
Hello Lavatoto,

Thank you for bringing this issue to my attention. It seems that the problem you're encountering with the `bip_utils` installation is related to compatibility issues with Python 3.12. Sometimes, newer Python versions introduce changes that can break compatibility with certain packages, especially if those packages haven't been updated to align with the new Python version.

#### **Suggested Solutions:**

1. **Use a Different Python Version**:
   - I recommend trying Python 3.9, which is known for its stability and broad compatibility with various packages, I am using Python 3.9 with the EnigmaCracker-Docker version.
   - You can download Python 3.9 from the [official Python website](https://www.python.org/downloads/release/python-390/).

2. **Setting Up a Virtual Environment**:
   - Using a virtual environment can help manage project-specific dependencies without affecting your global Python setup. Here's how you can set one up:
     ```bash
     # Create a virtual environment (ensure Python 3.9 is installed)
     python3.9 -m venv venv

     # Activate the virtual environment
     # On Windows
     venv\Scripts\activate
     # On macOS/Linux
     source venv/bin/activate

     # Now install bip_utils and the other imports within the virtual environment 
     pip install bip_utils
     pip install requests
     pip install python-dotenv
     ```

3. **Consider Using Docker**:
   - Alternatively, you might want to consider using the Docker version of EnigmaCracker. This way, you don’t have to worry about Python versions or dependency issues, as the Docker container will handle it for you.
   - If you're new to Docker, here's a brief guide to get started:
     - [Install Docker](https://docs.docker.com/get-docker/) if you haven’t already.
     - Use the guide I made in the `README.md` for using docker with EnigmaCracker [Running EnigmaCracker in Docker](https://github.com/yaron4u/EnigmaCracker?tab=readme-ov-file#running-enigmacracker-in-docker)

#### **Next Steps:**

- Please try the solutions above and let me know if the problem persists.
- If you encounter any issues or have further questions, don't hesitate to ask!
